### ISSUE TITLE
CyberTruck won't compile for WASM only

### ISSUE THREAD

**Issue by samcov** [unoplatform/cybertruck#23]
**I get the error**: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.Win32.Registry, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Development Environment**: VS 2019 16.3.10

**Project looks like the pic below**: 
![image](https://user-images.githubusercontent.com/1551314/70278040-58ad2000-1768-11ea-865c-a1881cc1efef.png)

**Comment by MatFillion** [comment]
Have you tried clicking here ? Let us know if it solves the issue. 
![image](https://user-images.githubusercontent.com/7029537/70345795-d20d4700-182a-11ea-8f83-0623b3ab04bc.png)

**Comment by jeromelaban** [comment]
@samcov also, make sure to not update the packages that are included in the solution, particularly the package for the console logging.

**Comment by agneszitte-nventive** [comment]
> Have you tried clicking here ? Let us know if it solves the issue.
> ![image](https://user-images.githubusercontent.com/7029537/70345795-d20d4700-182a-11ea-8f83-0623b3ab04bc.png)

Yes, you are maybe missing the web development workload (in the VisualStudio Installer) for your VisualStudio setup.
![image](https://user-images.githubusercontent.com/16295702/70346615-b60aa500-182c-11ea-9245-ac141d3b21f9.png)

**Comment by samcov** [comment]
**Guys, thanks for the quick response!**

@MatFillion @agneszitte-nventive I use the Asp.net & Web Dev workload all the time, it's not missing(see pic below). What I don't want installed is any UWP, Xamarin, or other unnecessary things to do simple WASM. 

@jeromelaban I didn't update any nugets, the remain the same.

![image](https://user-images.githubusercontent.com/1551314/70347726-062a3d00-1816-11ea-98c7-334fde4c6435.png)

**Comment by jeromelaban** [comment]
@samcov it feels like there's some missing system component that we did not account for. Can you make sure that in the installer .NET 4.6.2 is checked (both SDK and TargetingPack) ?

**Comment by agneszitte-nventive** [comment]
@samcov @jeromelaban 
I quickly test to install VS2019 Preview (Version 16.5.0 Preview 1.0) on the side with the same workloads selected as the screenshot above and I'm able to compile WASM with the Cybertruck solution without any issues or changes.
![image](https://user-images.githubusercontent.com/16295702/70349353-94142100-1832-11ea-84f8-b7fddedddf05.png)

**Comment by samcov** [comment]
@jeremiethibeault Neither were checked so I added both, but same issue.

@agneszitte-nventive Very interesting, I wonder what's missing...

**Comment by agneszitte-nventive** [comment]
@samcov Hum just curious if you can try to install VS2019 Preview (Version 16.5.0 Preview 1.0) on the side with the same workloads to see if you have the same results (in case you are able to install it).
I just not installed the "Desktop Development with C++" in this case since it was not needed ;), but all the others match yours.
I just picked the preview version to test because I already have VS2019 installed with other workloads (xamarin, visual studio extension, UWP,ect...).

**Comment by samcov** [comment]
@agneszitte-nventive I'll try that later and let you know. I'm also going to try it on another system where I have Xamarin, etc installed.

**Comment by samcov** [comment]
Tried it on one my desktops without Xamarin, etc., and it worked perfectly, so I'm calling this closed and I'll have to see what's different in my Surface development environment... see result below.
![image](https://user-images.githubusercontent.com/1551314/70370518-0c9fcf80-187d-11ea-98b3-ae22afab8df3.png)

**Comment by samcov** [comment]
Uno is AMAZING!!! On my full development machine, WASM & Droid!
**WASM**
![image](https://user-images.githubusercontent.com/1551314/70371059-dfeeb680-1882-11ea-9413-4ef4588d6e0d.png)

**DROID**
![image](https://user-images.githubusercontent.com/1551314/70371073-1debda80-1883-11ea-880d-3af5874f3761.png)

**Comment by samcov** [comment]
Ok, I figured out what was wrong, and it's NOT an Uno problem, likely a Visual Studio Issue.

**What doesn't work**: On my Surface laptop, The user is named "Firstname Lastname", note that this username has a space between first and last name, which is of course the directory name under "C:\Users", i.e. "C:\Users\Firstname Lastname". For whatever reason with Uno, it fails to find some things when this is the case.

**What does work**:  I created another user on the same machine named "FirstLast" no space inbetween, loaded the project into VS 2019, got the warning in yellow, but pressed F5 and everything worked as advertized!

**Observation**: What led me to this was 2 things. VS has trouble with some special characters, so I was suspicious anyway, but then I also noticed that on the two other machines where it worked without issue, the username had no spaces in the name.

I'll also post this in the main Uno issue, and while I think it's VS, it could also be a windows issue.

**Comment by agneszitte-nventive** [comment]
Thank you so much @samcov for taking the time to list all the details and testing UNO, I'm sure it will help another dev in the future if they encounter the same issue.
I hope you will continue to use and/or contribute to the platform and don't hesitate to come back to us if you have additional questions. ([How to contribute](https://github.com/unoplatform/uno/blob/af5365331d87a80ed4dd83b9e4839cc0d4a0ee5b/CONTRIBUTING.md))
For a more direct conversation, [our Gitter is also a good place to visit](https://gitter.im/uno-platform/Lobby).

**Comment by samcov** [comment]
I also want to thank you guys for helping me past the initial phase. When I tweeted that I was looking into Uno, I got a lot of interest for me to report how it went because they're waiting in the wings to try it themselves. I'll keep you guys informed!
